config/routes.rb
Memories::Application.routes.draw do

  resources :memory_infos

  match 'google', :controller => 'memory_infos', :action => 'google', :as => :google
  match 'memcreate', :controller => 'memory_infos', :action => 'mcreate', :as => :memcreate
  match 'memories', :controller => 'memory_infos', :action => 'memories', :as => :memories
  match 'memories_to_json', :controller => 'memory_infos', :action => 'memories_to_json', :as => :memories_to_json
  match 'login', :controller => 'login', :action => 'index', :as => :login
  match 'logout', :controller => 'login', :action => 'logout', :as => :logout
  match 'registe', :controller => 'login', :action => 'registe', :as => :registe
  match 'validate_email' => 'login#validate_email', :as => :validate_email
  match 'validate_name' => 'login#validate_name', :as => :validate_name
                

  root :to => "login#index"  

end

app/models/memory_info.rb
class MemoryInfo < ActiveRecord::Base
end

app/models/user.rb
# encoding: UTF-8

class User < ActiveRecord::Base

  validates_uniqueness_of :name, :message => "用户名已经被占用，换一下吧！"
  validates_presence_of(:name, :message => "用户名不能为空")
  validates_uniqueness_of :email, :message => "邮箱已经被占用，换一下吧！"
  validates_presence_of :email, :message => "邮箱不能为空" 
  validates_presence_of(:passwd, :message => "密码不能为空")
  validates_confirmation_of :passwd, :message => "两次密码输入不一致！"

  def before_save
    self.passwd = Digest::MD5.hexdigest(self.passwd)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/login_controller.rb
# encoding: UTF-8

class LoginController < ApplicationController

  skip_before_filter :login_check, :only => ["index", "registe", "validate_email", "validate_name"]

  def index
    @user = User.new({:gender => '男'})
    if request.post?
      if params[:user] && params[:user][:username] && params[:user][:passwd]
        if (@user = User.find_by_name(params[:user][:username])) && Digest::MD5.hexdigest(params[:user][:passwd]) == @user.passwd
          session[:user_id] = @user.id
          redirect_to memories_url
        else
          flash[:notice] = ""
        end
      else 
        flash[:notice] = ""
      end
    end
  end

  def registe
    @user = User.new
    if request.post?
      @user = User.new(params[:user])
      if @user.save
        session[:user_id] = @user.id
        redirect_to memories_url
      end
    end
  end

  def logout
    reset_session
    redirect_to login_url
  end

  def validate_email
    if params[:user] && params[:user][:email]
      if User.exists?(:email => params[:user][:email])
        render :layout => false, :text => ""
        return
      end
    end
    render :layout => false, :text => ''
  end

  def validate_name
    if params[:user] && params[:user][:name]
      if User.exists?(:name => params[:user][:name])
        render :layout => false, :text => ""
        return
      end
    end
    render :layout => false, :text => ''
  end
end

app/controllers/memory_infos_controller.rb
require 'json'

class MemoryInfosController < ApplicationController

  def memories
    if session[:user_id]
      @user = User.find(session[:user_id])
      @memories = MemoryInfo.all(:select => "id, lng, lat, address, mdate, content", :conditions => {:user_id => session[:user_id]}, :order => 'mdate')
      @json = @memories.collect {|mem| JSON(mem.to_json)['memory_info']}.to_json
    else
      @json = [].to_json
    end
  end

  def mcreate
    if request.post?
      memory = JSON params[:memory]
      @memory = MemoryInfo.new(memory)
      @memory.user_id = session[:user_id]
      if @memory.save
        render :json => JSON(@memory.to_json)['memory_info'].to_json, :status => 200
      else
        render :json => JSON(@memory.to_json)['memory_info'].to_json, :status => 500
      end
    end
  end

  def memories_to_json
    if session[:user_id]
      @user = User.find(session[:user_id])
      @memories = MemoryInfo.all(:select => "id, lng, lat, address, mdate, content", :conditions => {:user_id => session[:user_id]}, :order => 'mdate')
      @json = @memories.collect {|mem| JSON(mem.to_json)['memory_info']}.to_json
    else
      @json = [].to_json
    end
    render :status => 200, :json => @json
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>回忆-Memories</title>
  <%= stylesheet_link_tag 'scaffold' %>
  <%= javascript_include_tag 'prototype' %>
  <%= yield :head %>
</head>
<body>

<%= yield  %>

</body>
</html>

app/views/login/_form.html.erb
<% content_for :head do %>
<%= javascript_include_tag "validation_cn", "effects" %>
<%= stylesheet_link_tag "style_min" %>
<style>
  div#container {margin-left: 20px; margin-top: 5px; width: 100%; color: #aaa;}
  div#title {margin-left: 20px; font-size: 15px; color: #666;}
  div#title p {font-style: italic; line-height: 10px;}
  td.split {border: 0px; width: 1px; background-color: #a1a1a1;}
  td.item {text-align: right;}
  p.notice {width: 100%; text-align: center; color: red;}
</style>
<% end %>

<div id="title">
  <p style="text-indent: 4em;">在这里，在地图上记录下我们的过去，不论美好、快乐，还是伤感...</p>
  <p style="text-indent: 2em;">把它做为我们的财富，留给自己，留给家人，分享给每一位朋友...</p>
  <p>当我们闲暇时，让我们静静的回味着过去, 憧憬着未来...</p>
</div>
<div id="container">
<table>
  <tr>
    <td>
      <%= form_tag "/login", :id => 'loginform' do %>
        <p class="notice"><%= flash[:notice] %></p>
        <p>用户名：<input type="text" name="user[username]" class="required" /></p>
        <p>密&nbsp;&nbsp;&nbsp;码：<input type="password" name="user[passwd]" class="required" /></p>
        <input type="submit" value="提交" />
      <% end %>
    </td>
    <td class="split"></td>
    <td>
      <%= form_tag('/registe', :id => 'registeform') do %>
        <table>
          <tr>
            <td class="item">邮箱：</td>
            <td>
              <input type="text" name="user[email]" class="required validate-email validate-ajax-/validate_email" />
            </td>
          </tr>
          <tr>
            <td class="item">昵称：</td>
            <td><input type="text" name="user[name]" class="required validate-ajax-/validate_name" /></td>
          </tr>
          <tr>
            <td class="item">年龄：</td>
            <td><input type="text" name="user[age]" class="validate-number" /></td>
          </tr>
          <tr>
            <td class="item">性别：</td>
            <td>
              <input type="radio" name="user[gender]" value="女" />女
              <input type="radio" name="user[gender]" value="男" checked />男
            </td>
          </tr>
          <tr>
            <td class="item">密码：</td>
            <td>
              <input type="password" name="user[passwd]" id="password" class="required min-length-3 max-length-20">
            </td>
          </tr>
          <tr>
            <td class="item">确认密码：</td>
            <td>
              <input type="password" name="user[passwd_confirmation]" class="equals-password validation-failed">
            </td>
          </tr>
          <tr><td colspan="2"><input type="submit" value="注册" /><input type="reset" value="重置" /></td></tr>
        </table>
      <% end %>
    </td>
  </tr>
</table>
</div>
<script>
  new Validation('loginform');
  new Validation('registeform');
</script>

app/views/login/index.html.erb
<%= render :partial => "form" %>

app/views/login/registe.html.erb
<%= render :partial => "form" %>

app/views/memory_infos/edit.html.erb
<h1>Editing memory_info</h1>

<% form_for(@memory_info) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </p>
  <p>
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </p>
  <p>
    <%= f.label :mdate %><br />
    <%= f.date_select :mdate %>
  </p>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @memory_info %> |
<%= link_to 'Back', memory_infos_path %>

app/views/memory_infos/google.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map_canvas { height: 100% }
    </style>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.8.3.min.js"></script>
    <script type="text/javascript"
      src="http://maps.googleapis.com/maps/api/js?key=AIzaSyAMVTA7NrTr8UBzriytHYV6Kk7dWOxsJ-Q&sensor=false&language=zh">
    </script>
    <script type="text/javascript">
      $(function() {
        function initialize() {
          var mapOptions = {
            center: new google.maps.LatLng(-34.397, 150.644),
            zoom: 8,
            mapTypeId: google.maps.MapTypeId.ROADMAP
          };
          var map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
        }

        initialize();   
      });
    </script>
  </head>
  <body>
    <div id="map_canvas" style="width:100%; height:100%"></div>
  </body>
</html>

app/views/memory_infos/index.html.erb
<h1>Listing memory_infos</h1>

<table>
  <tr>
    <th>User</th>
    <th>Address</th>
    <th>Content</th>
    <th>Mdate</th>
  </tr>

<% for memory_info in @memory_infos %>
  <tr>
    <td><%=h memory_info.user_id %></td>
    <td><%=h memory_info.address %></td>
    <td><%=h memory_info.content %></td>
    <td><%=h memory_info.mdate %></td>
    <td><%= link_to 'Show', memory_info %></td>
    <td><%= link_to 'Edit', edit_memory_info_path(memory_info) %></td>
    <td><%= link_to 'Destroy', memory_info, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New memory_info', new_memory_info_path %>

app/views/memory_infos/memories.html.erb
<% content_for :head do %>
<script type="text/javascript" src="http://api.map.baidu.com/api?v=1.2"></script>
<script type="text/javascript" src="/javascripts/application.js"></script>
<style type="text/css">  
  html{height:100%}  
  body{height:100%;margin:0px;padding:0px}  
  #container{height:100%}  
  div#info {margin: 0px; position:fixed;z-index: 1; background-color: #fff; }
  a, a:hover, a:link a:visited {color: red;}
</style>
<script type="text/javascript">
  var map = null;
  var rails_token = "<%= form_authenticity_token %>";
  var init_data = "<%= @json %>";
  var opts = { width : 250, height: 105 }
  Event.observe(window, 'load', function() {
    map = new BMap.Map("container");          // 创建地图实例  
    map.enableScrollWheelZoom();  // 开启鼠标滚轮缩放  
    map.enableContinuousZoom();   // 开启连续缩放效果  
    map.enableInertialDragging(); // 开启惯性拖拽效果  
    var point = new BMap.Point(116.404, 39.915);  // 创建点坐标 
    map.centerAndZoom(point, 5);                 // 初始化地图，设置中心点坐标和地图级别
    play_memories(-1000, false);
    add_memories_event();
  });
</script>
<% end %>

<div id="info">
  <% if session[:user_id] %>
    <b>Name:</b><%=h @user.name %>&nbsp;<b>Age:</b><%=h @user.age %>&nbsp;<b>Gender:</b><%=h @user.gender %>
    <a href="javascript:void(0);" style="display: none" id="mem_btn">开启记忆</a>
    <a href="javascript:void(0);" onclick="play_memories(2000, true)">播放</a>
    <a href="javascript:void(0);" onclick="if (confirm('确认退出吗？')) location.href='/logout';">退出</a>
  <% else %>
    <a href="/login">登录/注册</a>
  <% end %>
</div>

<div id="container"></div>

app/views/memory_infos/new.html.erb
<h1>New memory_info</h1>

<% form_for(@memory_info) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </p>
  <p>
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </p>
  <p>
    <%= f.label :mdate %><br />
    <%= f.date_select :mdate %>
  </p>
  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', memory_infos_path %>

app/views/memory_infos/show.html.erb
<p>
  <b>User:</b>
  <%=h @memory_info.user_id %>
</p>

<p>
  <b>Address:</b>
  <%=h @memory_info.address %>
</p>

<p>
  <b>Content:</b>
  <%=h @memory_info.content %>
</p>

<p>
  <b>Mdate:</b>
  <%=h @memory_info.mdate %>
</p>


<%= link_to 'Edit', edit_memory_info_path(@memory_info) %> |
<%= link_to 'Back', memory_infos_path %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<% form_for(@user) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </p>
  <p>
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :lon %><br />
    <%= f.text_field :lon %>
  </p>
  <p>
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </p>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Address</th>
    <th>Lon</th>
    <th>Lat</th>
  </tr>

<% for user in @users %>
  <tr>
    <td><%=h user.name %></td>
    <td><%=h user.age %></td>
    <td><%=h user.address %></td>
    <td><%=h user.lon %></td>
    <td><%=h user.lat %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New user', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<% form_for(@user) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </p>
  <p>
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :lon %><br />
    <%= f.text_field :lon %>
  </p>
  <p>
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </p>
  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% content_for :head do %>
<script type="text/javascript" src="http://api.map.baidu.com/api?v=1.2"></script>
<style type="text/css">  
  html{height:100%}  
  body{height:100%;margin:0px;padding:0px}  
  #container{height:100%}  
  div#info {margin: 0px; position:fixed;z-index: 1; background-color: #fff; }
</style>
<script type="text/javascript">
  var rails_token = "<%= form_authenticity_token %>";
  var rails_form = function(rails_token, url) {
    var form = document.createElement("form");
    form.setAttribute("action", url);
    form.setAttribute("method", "post");

    var hidden = document.createElement("input");
    hidden.setAttribute("name", "authenticity_token");
    hidden.setAttribute("value", rails_token);
    hidden.setAttribute("type", "hidden");
    form.appendChild(hidden);

    return form;
  }

  var create_form = function(e) {
    var form = rails_form(rails_token, "/users/mcreate");

    form.innerHTML += "地址:";

    var input = document.createElement("input");
    input.setAttribute("type", "text");
    input.setAttribute("name", "memory[address]");
    form.appendChild(input);

    form.innerHTML += "<br />描述:";

    var input = document.createElement("input");
    input.setAttribute("type", "text");
    input.setAttribute("name", "memory[content]");
    form.appendChild(input);

    form.innerHTML += "<br />时间:";

    var input = document.createElement("input");
    input.setAttribute("type", "text");
    input.setAttribute("name", "memory[mdate]");
    form.appendChild(input);

    var input = document.createElement("input");
    input.setAttribute("type", "hidden");
    input.setAttribute("name", "memory[lon]");
    input.setAttribute("value", e.point.lng);
    form.appendChild(input);

    var input = document.createElement("input");
    input.setAttribute("type", "hidden");
    input.setAttribute("name", "momory[lat]");
    input.setAttribute("value", e.point.lat);
    form.appendChild(input);

    var submit = document.createElement("input");
    input.setAttribute("type", "button");
    input.setAttribute("value", "记忆");
    input.addEventListener("click", function() {
      alert('aaa');
    });

    var container = document.createElement("div");
    container.appendChild(form);

    return container.innerHTML;
  }
</script>
<% end %>

<div id="info">
  <b>Name:</b><%=h @user.name %>&nbsp;<b>Age:</b><%=h @user.age %>&nbsp;<b>Gender:</b><%=h @user.gender %>
  <a href="/login/logout">退出</a>
</div>

<div id="container"></div>
<script type="text/javascript">  
  var map = new BMap.Map("container");          // 创建地图实例  
  map.enableScrollWheelZoom();  // 开启鼠标滚轮缩放  
  map.enableKeyboard();         // 开启键盘控制  
  map.enableContinuousZoom();   // 开启连续缩放效果  
  map.enableInertialDragging(); // 开启惯性拖拽效果  
  var point = new BMap.Point(116.404, 39.915);  // 创建点坐标 
  map.centerAndZoom(point, 5);                 // 初始化地图，设置中心点坐标和地图级别  
  map.addEventListener("click", function(e){  
    var opts = {
      width : 250,     // 信息窗口宽度
      height: 150,     // 信息窗口高度
    }
    var infoWindow = new BMap.InfoWindow(create_form(e), opts);  // 创建信息窗口对象
    map.openInfoWindow(infoWindow, e.point);      // 打开信息窗口
  }); 
</script>